#!/bin/sh

echo $'Ah ben c\'est bien Nils !'
sleep 2
echo $'Super !'
sleep 1
echo $'L\'appareil photo il est foutu mais on s\'en fout !'
sleep 3
echo $'Oh t\'es vraiment qu\'un sale petit con !'
sleep 2
