CXX = g++
CXXFlAGS = -Wall -Wextra -Werror -std=c++17 -pedantic

VPATH = tests

EXEC = 
TEST = testsuite

.PHONY: all test clean

all: $(EXEC)

test: $(TEST)

clean:
	${RM} $(OBJ)
	${RM} $(EXEC)
	${RM} $(TEST)
